### ISSUE TITLE
Make a hex sticker!

### ISSUE THREAD

**Issue by jacquietran** [jacquietran/wnblr#11]

**Comment by PythonCoderUnicorn** [comment]
Hello friend,

this is an issue i can help with, commenting here for record.

I have 2 designs ready to upload upon your **Discord** initial review process. 🍁

**Comment by PythonCoderUnicorn** [comment]
Hello friend again,

design 1
![wnblr 1](https://user-images.githubusercontent.com/55933131/143320204-1b71cdca-40d7-4213-832a-b528efc220f8.png)

**Comment by PythonCoderUnicorn** [comment]
Hello friend, 

design 2
![wnblr 2](https://user-images.githubusercontent.com/55933131/143320254-abcbcd6d-a626-4abb-9018-240b3dcf879d.png)

**Comment by jacquietran** [comment]
@PythonCoderUnicorn from dowwwwwwwwn towwwwwwwwnnnnnnnn!!!

these are so amazing, i love them both. i'll find a way to incorporate both designs into my package docs and eventual {pkgdown} website.

is it too keen of me if i start a sticker shop? lol

**Comment by PythonCoderUnicorn** [comment]
> is it too keen of me if i start a sticker shop? lol

 i also know web dev, i have a website but R makes web dev so easy which is awesome

**Comment by jacquietran** [comment]
yeah it's so fun making websites with R!
