### ISSUE TITLE
Shot location variables - convert to distance measurements

### ISSUE THREAD

**Issue by davescroggs** [jacquietran/wnblr#28]
Currently the x, y coordinates in the "shots" data frame are between 0-100. Would it be possible to convert to physical distance measurements to make court locations easier to manage? [Wikipedia](https://en.wikipedia.org/wiki/Basketball_court) has the length (long edge) of the court as 28 m and width (short) as 15 m.

**Comment by jacquietran** [comment]
great suggestion @davescroggs, will definitely incorporate this into the next release!!
