### ISSUE TITLE
Here is my R Repo for your (Part 1) package

### ISSUE THREAD

**Issue by davidjayjackson** [jacquietran/wnblr#30]
You have done a really good job scrapping that data.

https://github.com/davidjayjackson/streamRs-jacquietran.git

David

**Comment by jacquietran** [comment]
hi david! thanks for dropping by - i clicked on your link and i can only see an empty repo, is there meant to be something there?

**Comment by davidjayjackson** [comment]
Ok, Check it now. 
Here is the video from last night's stream.
https://www.twitch.tv/videos/1221431265?t=02h11m42s

**Comment by jacquietran** [comment]
oh cool i see your explorations now, thanks @davidjayjackson! i appreciate you trying out the package!! 😸
